language: python
python:
  - 3.6
  - 3.7

before_install:
  - sudo apt-get install -y tidy
  - sudo apt-get install -y swig
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y libreoffice python3-uno
  - libreoffice '--accept=socket,host=127.0.0.1,port=8100;urp;' &

install:
  - pip install -U setuptools
  - pip install coveralls
  - # pip install Django==$DJANGO
  - # if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install -r requirements.python3.txt; else pip install -r requirements.txt;  fi
#   - test -e "requirements.$TRAVIS_BRANCH.txt" && ( pip install -r "requirements.$TRAVIS_BRANCH.txt" ) || ( pip install -r requirements.txt )
  - pip install -e .
  - pip freeze

script:
  - export LINO_CACHE_ROOT=$TRAVIS_BUILD_DIR/lino_cache
  - mkdir $LINO_CACHE_ROOT
  - inv cov --no-html
#  - inv prep test
#  - python setup.py test

# if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then inv cov; fi;

after_success:
  - coveralls
